apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova2
  
resources:
  - namespace.yml

bases:
  - ../../bases

patchesStrategicMerge:
  - patches/whoami/ingress.yml
  - patches/common/configmap.yml
