apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova
  
resources:
  - namespace.yml
  - resources/whoami2/deployment.yml
  - resources/whoami2/service.yml
  - resources/whoami2/ingress.yml

bases:
  - ../../bases

patchesStrategicMerge:
  - patches/whoami/ingress.yml
  - patches/common/configmap.yml

configMapGenerator:
- name: db-config 
  files:
  - resources/whoami2/db.sh